#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=ExampleJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/uvadlx_practicals_2025
# Activate your environment
source activate dl2025
python assignment1/train_mlp_numpy_1.py