#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=MLPCPU
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/uvadlc_practicals_2025/assignment3/part2
# Activate your environment
source activate dl2025
srun bash run_adv_eval.sh
